### ISSUE TITLE
Script hangs while handling large amount of sRNA files

### ISSUE THREAD

**Issue by pupatel** [atulkakrana/PHASIS#4]
I'm using PHASdetect for n~100 sRNA libraries. The script hangs while processing these large amount of libraries. However, I do see results folder being generated and see the output for every sRNA library in it.
The issue is it's the finishing analysis, but not showing on screen (just hangs there) for many sRNA libraries.

Thanks
Parth.

**Comment by atulkakrana** [comment]
Thanks Parth. We are aware of issue - on certain systems or python versions. The fix will be released on next point release.  Until then, we will switch to serial mode for corresponding step in analysis. I will post here, when patched version is uploaded.

Atul

**Comment by atulkakrana** [comment]
Parth - Did the patched version worked? I sent it through e-mail. Please confirm so that bug could be closed

**Comment by atulkakrana** [comment]
Resolving  due to lack of response. Patch for this sent to user. Patch needs to be applied to scripts.

Atul
