### ISSUE TITLE
phasmerge, ValueError: too many values to unpack (expected 2)

### ISSUE THREAD

**Issue by radio1988** [atulkakrana/PHASIS#6]
After phasdetect reported a successful run, I type the next command:
'python3 phasmerge -mode merge -dir phased_04_26_21_06'
Similar command gave me correct result with test dataset, but I got the following messages:

#### Fn: checkLibs ###########################
--Python v3.0 or higher          : found

#### Fn: Settings Reader ####################
User Input runType               : S
User Input reference             : ABD_Genome.20170209.fa
User Input Libs:                 : WheatsRNA_tagcount.txt
User Input for library type      : T
User Input for phase length      : 21
User Input index location        : None

#### Fn: pvalue capture ###################
Total 10 clusters cached at different p-values: 0.005, 0.001, 0.0005, 0.0001, 5e-05, 1e-05, 5e-06, 1e-06, 5e-07, 1e-07
Best guessed p-value being used: 1e-06
User can specify a lower or higher p-val cutoff using '-pval' option

#### Fn: prepare ############################
WARNING: Temporary files exits from earlier run, these will be deleted
1 list files found
10 clust files found
--1 files prepared for collapsing
--Working folder:summary_04_26_21_10 | Temporary Folder:./summary_04_26_21_10/temp

List files selected for analysis - Converting them to readable format
Total files to analyze: 1

#### Fn: listConvertor ####################
Traceback (most recent call last):
  File "phasmerge.py", line 2704, in <module>
  File "phasmerge.py", line 2484, in main
  File "phasmerge.py", line 747, in listConverter
ValueError: too many values to unpack (expected 2)

Is there something I can do to fix this ?

Thanks!

**Comment by atulkakrana** [comment]
Hi Radio,

This part of *phasmerge* is very well tested, and for very long time, so you shouldn't see any issues. Could you please attach the files ending with "PARE.validation.list"? These files will be in `phased_04_26_21_06` directory. To attach, you can upload to Google Drive or other service and post the link here.

By the way did you tried running *phasdetect* on all the sRNA libraries and then use *phasmerge*? or on the combined file of sRNAs? Since, now index has been made all these runs should be fast.

Atul

**Comment by radio1988** [comment]
Thank Atul! 

The file link is: https://drive.google.com/file/d/0B_guOsz_7aU4UFdURnBmWmdyZkU/view?usp=sharing 

The file list in the folder 'phased_04_26_21_06' is:

-rw-rw-r-- 1 rui rui 275K Apr 26 21:09 WheatsRNA_tagcount.txt.score_p0.005_sRNA_21_out.txt
-rw-rw-r-- 1 rui rui  25M Apr 26 21:09 WheatsRNA_tagcount.txt.output_all_sRNA_21_out.txt
-rw-rw-r-- 1 rui rui  241 Apr 26 21:09 WheatsRNA_tagcount.txt.summary.sRNA.v1.txt
-rw-rw-r-- 1 rui rui  57K Apr 26 21:09 WheatsRNA_tagcount.txt.score_p5e-07_sRNA_21_out.cluster
-rw-rw-r-- 1 rui rui  53K Apr 26 21:09 WheatsRNA_tagcount.txt.score_p1e-07_sRNA_21_out.cluster
-rw-rw-r-- 1 rui rui  71K Apr 26 21:09 WheatsRNA_tagcount.txt.score_p5e-06_sRNA_21_out.cluster
-rw-rw-r-- 1 rui rui  60K Apr 26 21:09 WheatsRNA_tagcount.txt.score_p1e-06_sRNA_21_out.cluster
-rw-rw-r-- 1 rui rui  72K Apr 26 21:09 WheatsRNA_tagcount.txt.score_p1e-05_sRNA_21_out.cluster
-rw-rw-r-- 1 rui rui  88K Apr 26 21:09 WheatsRNA_tagcount.txt.score_p5e-05_sRNA_21_out.cluster
-rw-rw-r-- 1 rui rui  95K Apr 26 21:09 WheatsRNA_tagcount.txt.score_p0.0001_sRNA_21_out.cluster
-rw-rw-r-- 1 rui rui 101K Apr 26 21:09 WheatsRNA_tagcount.txt.score_p0.0005_sRNA_21_out.cluster
-rw-rw-r-- 1 rui rui 102K Apr 26 21:09 WheatsRNA_tagcount.txt.score_p0.001_sRNA_21_out.cluster
-rw-rw-r-- 1 rui rui 132K Apr 26 21:09 WheatsRNA_tagcount.txt.score_p0.005_sRNA_21_out.cluster
-rw-rw-r-- 1 rui rui  32K Apr 26 21:09 WheatsRNA_tagcount.txt.cluster.boundary.without.PARE.validation.list

**Comment by radio1988** [comment]
We will run all 12 libraries soon today. The error we got now is for a combined library.

**Comment by atulkakrana** [comment]
Hi Radio,

Apologies for delay in response. I have a serious deadline next week and might get back to you after that. I am really sorry about it.

Atul

**Comment by radio1988** [comment]
Hi Atul,

Thanks for looking into this!

Radio

**Comment by atulkakrana** [comment]
Radio,

I am committed to resolve this issue. I will install Ubuntu as virtual machine and test PHASIS with your library. Please give me time till Thursday, I am wrapping up stuff for my deadline. Thanks for your patience.

Atul

**Comment by atulkakrana** [comment]
Hi Radio,

Sorry for late response. I checked the file you put on Google Drive. It seems that file got corrupt. Did you open the file in some program like Excel or Openoffice? The reason I am asking is because that file has commas in it, whereas the file from *phasdetect* is space separated. So, something went wrong with the results.

I would suggest you to rerun the *phasdetect* and use *phasmerge* on the new folder.

Atul

**Comment by atulkakrana** [comment]
Closing this bug for lack of activity. Please, reopen if the problem still exists. Atul
